routes/web.php
<?php

// use App\Role; // called role model
// use App\User;

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
    // $user = Auth::user();

    // if($user->isAdmin()) {
    //     echo 'this user is an Administrator';
    // }

    // if(Auth::check()) {
    //     return 'the user is logged in'; //another of checking the user is logged in
    // }

    //or
    // $username = 'dora';
    // $password = '3tft3rftgt';
    // if(Auth::attempt(['username'=>$username,'password'=>$password])) {
    //     return redirect()->intended('/admin');
    // }

// });

Auth::routes();

Route::get('/', 'HomeController@index')->name('home');


// Route::get('/admin/user/roles', ['middleware'=>'role', function() {
//     return "Middleware role";
// }]);

Route::get('/post/{id}', ['as'=>'home.post', 'uses'=>'AdminPostsController@post']);

Route::group(['middleware'=>'isAdmin'], function(){

    Route::get('/admin', 'AdminController@index');
    
    Route::resource('/admin/users', 'AdminUsersController');
    
    Route::resource('/admin/posts', 'AdminPostsController');

    Route::resource('/admin/categories', 'AdminCategoriesController');

    Route::resource('/admin/media', 'AdminMediaController');

    // Route::get('/admin/media/upload', ['as'=>'media.upload', 'uses'=>'AdminMediaController@store']);

    Route::delete('/delete/media', 'AdminMediaController@deleteMedia');

    Route::resource('/admin/comments', 'PostCommentsController');

    Route::resource('/admin/comment/replies', 'CommentRepliesController');




});

Route::group(['middleware'=>'auth'], function() {

    Route::post('/comment/reply', 'CommentRepliesController@createReply');
    
});

Route::group(['prefix' => 'laravel-filemanager', 'middleware' => ['web', 'auth']], function () {
    \UniSharp\LaravelFilemanager\Lfm::routes();
});

app/Comment.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Comment extends Model
{
    //

    protected $fillable = [
        'post_id',
        'is_active',
        'author',
        'email',
        'photo',
        'body'
    ];

    public function replies() {
        return $this->hasMany('App\CommentReply');
    }

    public function post() {
        return $this->belongsTo('App\Post');
    }
}

resources/views/admin/comments/index.blade.php
@extends('layouts.admin')

@section('content')

    <!-- @if(Session::has('deleted_media'))
        <p class="bg-danger">{{session('deleted_media')}}</p>
    @endif -->

    <h1>Comments</h1>

    <style>
        
        table {
            font-family: arial, sans-serif;
            border-collapse: collapse;
            width: 100%;
        }

        td, th {
            border: 1px solid #dddddd;
            text-align: left;
            padding: 8px;
        }

        tr:nth-child(even) {
            background-color: #dddddd;
        }

    </style>

    @if(count($comments) > 0)

    <table style="width:100%">
        <tr>
            <th>Id</th>
            <th>Author</th>
            <th>Email</th>
            <th>Body</th>
            <th>Post</th>
            <th>Replies</th>
            <th>Created</th>
            <th>Updated</th>
            <th>Aprrove</th>
            <th>Delete</th>
        </tr>

            @foreach($comments as $comment)
        <tr>
            <td>{{$comment->id}}</td>
            <td>{{$comment->author}}</td>
            <td>{{$comment->email}}</td>
            <td>{{Str::limit($comment->body, 10)}}</td>
            <td><a href="{{route('home.post', $comment->post->slug)}}">View post</a></td>
            <td><a href="{{route('replies.show', $comment->id)}}">View replies</a></td>
            <td>{{$comment->created_at->diffForHumans()}}</td>
            <td>{{$comment->updated_at->diffForHumans()}}</td>
            <td>
                @if($comment->is_active == 1)

                    {{ Form::open(['method'=>'PATCH', 'action'=>['PostCommentsController@update', $comment->id]]) }}
            
                        <input type="hidden" name="is_active" value="0">
                        <div class="form-group">
                            {{ Form::submit('Unapprove', ['class'=>'btn btn-success'])}}
                        </div>

                    {{ Form::close() }}

                    @else

                    {{ Form::open(['method'=>'PATCH', 'action'=>['PostCommentsController@update', $comment->id]]) }}
            
                        <input type="hidden" name="is_active" value="1">
                        <div class="form-group">
                            {{ Form::submit('Approve', ['class'=>'btn btn-info'])}}
                        </div>

                    {{ Form::close() }}

                @endif
            </td>
            <td>
                {{ Form::open(['method'=>'DELETE', 'action'=>['PostCommentsController@destroy', $comment->id]]) }}
                
                    <div class="form-group">
                        {{ Form::submit('Delete', ['class'=>'btn btn-danger'])}}
                    </div>

                {{ Form::close() }}
            </td>
        </tr>
            @endforeach
    </table>
    
    @else
    <h3>No comments</h1>

    @endif

@endsection

resources/views/admin/comments/show.blade.php
@extends('layouts.admin')

@section('content')

    <!-- @if(Session::has('deleted_media'))
        <p class="bg-danger">{{session('deleted_media')}}</p>
    @endif -->

    <h1>Comments</h1>

    <style>
        
        table {
            font-family: arial, sans-serif;
            border-collapse: collapse;
            width: 100%;
        }

        td, th {
            border: 1px solid #dddddd;
            text-align: left;
            padding: 8px;
        }

        tr:nth-child(even) {
            background-color: #dddddd;
        }

    </style>

    @if(count($comments) > 0)

    <table style="width:100%">
        <tr>
            <th>Id</th>
            <th>Author</th>
            <th>Email</th>
            <th>Body</th>
            <th>Post</th>
            <th>Replies</th>
            <th>Created</th>
            <th>Updated</th>
            <th>Aprrove</th>
            <th>Delete</th>
        </tr>

            @foreach($comments as $comment)
        <tr>
            <td>{{$comment->id}}</td>
            <td>{{$comment->author}}</td>
            <td>{{$comment->email}}</td>
            <td>{{Str::limit($comment->body, 10)}}</td>
            <td><a href="{{route('home.post', $comment->post->slug)}}">View post</a></td>
            <td><a href="{{route('replies.show', $comment->id)}}">View replies</a></td>
            <td>{{$comment->created_at->diffForHumans()}}</td>
            <td>{{$comment->updated_at->diffForHumans()}}</td>
            <td>
                @if($comment->is_active == 1)

                    {{ Form::open(['method'=>'PATCH', 'action'=>['PostCommentsController@update', $comment->id]]) }}
            
                        <input type="hidden" name="is_active" value="0">
                        <div class="form-group">
                            {{ Form::submit('Unapprove', ['class'=>'btn btn-success'])}}
                        </div>

                    {{ Form::close() }}

                    @else

                    {{ Form::open(['method'=>'PATCH', 'action'=>['PostCommentsController@update', $comment->id]]) }}
            
                        <input type="hidden" name="is_active" value="1">
                        <div class="form-group">
                            {{ Form::submit('Approve', ['class'=>'btn btn-info'])}}
                        </div>

                    {{ Form::close() }}

                @endif
            </td>
            <td>
                {{ Form::open(['method'=>'DELETE', 'action'=>['PostCommentsController@destroy', $comment->id]]) }}
                
                    <div class="form-group">
                        {{ Form::submit('Delete', ['class'=>'btn btn-danger'])}}
                    </div>

                {{ Form::close() }}
            </td>
        </tr>
            @endforeach
    </table>
    
    @else
    <h3>No comments</h1>

    @endif

@endsection