routes/web.php
<?php

// use App\Role; // called role model
// use App\User;

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
    // $user = Auth::user();

    // if($user->isAdmin()) {
    //     echo 'this user is an Administrator';
    // }

    // if(Auth::check()) {
    //     return 'the user is logged in'; //another of checking the user is logged in
    // }

    //or
    // $username = 'dora';
    // $password = '3tft3rftgt';
    // if(Auth::attempt(['username'=>$username,'password'=>$password])) {
    //     return redirect()->intended('/admin');
    // }

// });

Auth::routes();

Route::get('/', 'HomeController@index')->name('home');


// Route::get('/admin/user/roles', ['middleware'=>'role', function() {
//     return "Middleware role";
// }]);

Route::get('/post/{id}', ['as'=>'home.post', 'uses'=>'AdminPostsController@post']);

Route::group(['middleware'=>'isAdmin'], function(){

    Route::get('/admin', 'AdminController@index');
    
    Route::resource('/admin/users', 'AdminUsersController');
    
    Route::resource('/admin/posts', 'AdminPostsController');

    Route::resource('/admin/categories', 'AdminCategoriesController');

    Route::resource('/admin/media', 'AdminMediaController');

    // Route::get('/admin/media/upload', ['as'=>'media.upload', 'uses'=>'AdminMediaController@store']);

    Route::delete('/delete/media', 'AdminMediaController@deleteMedia');

    Route::resource('/admin/comments', 'PostCommentsController');

    Route::resource('/admin/comment/replies', 'CommentRepliesController');




});

Route::group(['middleware'=>'auth'], function() {

    Route::post('/comment/reply', 'CommentRepliesController@createReply');
    
});

Route::group(['prefix' => 'laravel-filemanager', 'middleware' => ['web', 'auth']], function () {
    \UniSharp\LaravelFilemanager\Lfm::routes();
});

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'role_id', 'photo_id', 'is_active'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function role() {
        return $this->belongsTo('App\Role');
    }

    public function isAdmin() {
        if($this->role->name == 'Administrator' && $this->is_active == 1) {
            return true;
        }
        return false;
    }

    public function photo() {
        return $this->belongsTo('App\Photo');
    }

    public function posts() {
        return $this->hasMany('App\Post');
    }

    // public function getGravatarAttribute() {
    //     $hash = md5(strtolower(trim($this->attributes['email'])));

    //     return "https://gravatar.com/avatar/$hash";
    // }
}

resources/views/admin/users/create.blade.php
@extends('layouts.admin')

@section('content')

    <h1>Create Users</h1>

    <div class="row">
        @include('includes.form_error')
    </div>

    <div class="row">

        {{ Form::open(['method'=>'POST', 'action'=>'AdminUsersController@store', 'files'=>true]) }}
            
            <div class="form-group">
                {{ Form::label('name', 'Name:') }}
                {{ Form::text('name', null, ['class'=>'form-control'])}}
        
            </div>
            <div class="form-group">
                {{ Form::label('email', 'Email:') }}
                {{ Form::email('email', null, ['class'=>'form-control'])}}
        
            </div>
            <div class="form-group">
                {{ Form::label('role_id', 'Role:') }}
                {{ Form::select('role_id', [''=>'choose options'] + $roles, null, ['class'=>'form-control'])}}
            </div>
            <div class="form-group">
                {{ Form::label('is_active', 'Status:') }}
                {{ Form::select('is_active', [1 => 'Active', 0 => 'Not Active'], 0, ['class'=>'form-control'])}} <!-- the null can serve as default value by change it to 0 or 1 -->
            </div>
            <div class="form-group">
                {{ Form::label('photo_id', 'Upload Photo:') }}
                {{ Form::file('photo_id', ['class'=>'form-control'])}} <!-- the null can serve as default value by change it to 0 or 1 -->
            </div>
            <div class="form-group">
                {{ Form::label('password', 'Password:') }}
                {{ Form::password('password', ['class'=>'form-control'])}} <!-- the null can serve as default value by change it to 0 or 1 -->
            </div>
            <!-- <div class="form-group">
                {{ Form::file('file', ['class'=>'form-control'])}}
            
            </div> -->
            <div class="form-group">
                {{ Form::submit('Create User', ['class'=>'btn btn-primary'])}}
            </div>

            
            <!-- <input type="submit" name="submit"> -->
        {{ Form::close() }}
    </div>

@endsection

resources/views/admin/users/edit.blade.php
@extends('layouts.admin')

@section('content')

    <h1>Edit User</h1><br>

    <div class="row">
        @include('includes.form_error')
    </div>

    <div class="row">
        <div class="col-sm-2">
        
            <img src="{{$user->photo ? $user->photo->file : 'No Photo found'}}" height="100">

        </div>

        <div class="col-sm-10">
            {{ Form::model($user, ['method'=>'PATCH', 'action'=>['AdminUsersController@update', $user->id], 'files'=>true]) }}
                
                <div class="form-group">
                    {{ Form::label('name', 'Name:') }}
                    {{ Form::text('name', null, ['class'=>'form-control'])}}
            
                </div>
                <div class="form-group">
                    {{ Form::label('email', 'Email:') }}
                    {{ Form::email('email', null, ['class'=>'form-control'])}}
            
                </div>
                <div class="form-group">
                    {{ Form::label('role_id', 'Role:') }}
                    {{ Form::select('role_id', [''=>'choose options'] + $roles, null, ['class'=>'form-control'])}}
                </div>
                <div class="form-group">
                    {{ Form::label('is_active', 'Status:') }}
                    {{ Form::select('is_active', [1 => 'Active', 0 => 'Not Active'], null, ['class'=>'form-control'])}} <!-- the null can serve as default value by change it to 0 or 1 -->
                </div>
                <div class="form-group">
                    {{ Form::label('photo_id', 'Upload Photo:') }}
                    {{ Form::file('photo_id', ['class'=>'form-control'])}} 
                </div>
                <div class="form-group">
                    {{ Form::label('password', 'Password:') }}
                    {{ Form::password('password', ['class'=>'form-control'])}}
                </div>
                <div class="form-group">
                    {{ Form::submit('Update User', ['class'=>'btn btn-primary col-sm-6'])}}
                </div>
            {{ Form::close() }}

            {{ Form::open(['method'=>'DELETE', 'action'=>['AdminUsersController@destroy', $user->id]]) }}
                
                <div class="form-group">
                    {{ Form::submit('Delete User', ['class'=>'btn btn-danger col-sm-6'])}}
                </div>

            {{ Form::close() }}
        </div>
    </div>

@endsection

resources/views/admin/users/index.blade.php
@extends('layouts.admin')

@section('content')

    @if(Session::has('deleted_user'))
        <p class="bg-danger">{{session('deleted_user')}}</p>
    @endif

    <h1>Users</h1>

    <style>
        
        table {
            font-family: arial, sans-serif;
            border-collapse: collapse;
            width: 100%;
        }

        td, th {
            border: 1px solid #dddddd;
            text-align: left;
            padding: 8px;
        }

        tr:nth-child(even) {
            background-color: #dddddd;
        }

    </style>

    <table style="width:100%">
        <tr>
            <th>Id</th>
            <th>Photo</th>
            <th>Name</th>
            <th>Email</th>
            <th>Role</th>
            <th>Status</th>
            <th>Created</th>
            <th>Updated</th>
        </tr>

        @if($users)
            @foreach($users as $user)
        <tr>
            <td>{{$user->id}}</td>
            <td><img src="{{$user->photo ? $user->photo->file : 'No Photo found'}}" alt="" height="50"></td> <!-- if user photo exist(?) print out the user photo from file attribute in database or else(:) print out "No photo found"-->
            <td><a href="{{route('users.edit', $user->id)}}">{{$user->name}}</a></td>
            <td>{{$user->email}}</td>
            <td>{{$user->role->name}}</td>
            <td>{{$user->is_active == 1 ? 'Active' : 'Not Active'}}</td>
            <td>{{$user->created_at->diffForHumans()}}</td>
            <td>{{$user->updated_at->diffForHumans()}}</td>
        </tr>
            @endforeach
        @endif
    </table>

@endsection