routes/web.php
<?php

// use App\Role; // called role model
// use App\User;

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
    // $user = Auth::user();

    // if($user->isAdmin()) {
    //     echo 'this user is an Administrator';
    // }

    // if(Auth::check()) {
    //     return 'the user is logged in'; //another of checking the user is logged in
    // }

    //or
    // $username = 'dora';
    // $password = '3tft3rftgt';
    // if(Auth::attempt(['username'=>$username,'password'=>$password])) {
    //     return redirect()->intended('/admin');
    // }

// });

Auth::routes();

Route::get('/', 'HomeController@index')->name('home');


// Route::get('/admin/user/roles', ['middleware'=>'role', function() {
//     return "Middleware role";
// }]);

Route::get('/post/{id}', ['as'=>'home.post', 'uses'=>'AdminPostsController@post']);

Route::group(['middleware'=>'isAdmin'], function(){

    Route::get('/admin', 'AdminController@index');
    
    Route::resource('/admin/users', 'AdminUsersController');
    
    Route::resource('/admin/posts', 'AdminPostsController');

    Route::resource('/admin/categories', 'AdminCategoriesController');

    Route::resource('/admin/media', 'AdminMediaController');

    // Route::get('/admin/media/upload', ['as'=>'media.upload', 'uses'=>'AdminMediaController@store']);

    Route::delete('/delete/media', 'AdminMediaController@deleteMedia');

    Route::resource('/admin/comments', 'PostCommentsController');

    Route::resource('/admin/comment/replies', 'CommentRepliesController');




});

Route::group(['middleware'=>'auth'], function() {

    Route::post('/comment/reply', 'CommentRepliesController@createReply');
    
});

Route::group(['prefix' => 'laravel-filemanager', 'middleware' => ['web', 'auth']], function () {
    \UniSharp\LaravelFilemanager\Lfm::routes();
});

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    //
    protected $fillable = [
        'name'
    ];
}

resources/views/admin/categories/edit.blade.php
@extends('layouts.admin')

@section('content')

    <h1>Edit Categories</h1>

    {{ Form::model($category, ['method'=>'PATCH', 'action'=>['AdminCategoriesController@update', $category->id]]) }}
                
        <div class="form-group">
            {{ Form::label('name', 'Name:') }}
            {{ Form::text('name', null, ['class'=>'form-control'])}}
    
        </div>
        <div class="form-group">
            {{ Form::submit('Update Category', ['class'=>'btn btn-primary col-sm-6'])}}
        </div>

    {{ Form::close() }}

    {{ Form::open(['method'=>'DELETE', 'action'=>['AdminCategoriesController@destroy', $category->id]]) }}
                
        <div class="form-group">
            {{ Form::submit('Delete Category', ['class'=>'btn btn-danger col-sm-6'])}}
        </div>

    {{ Form::close() }}

@endsection

resources/views/admin/categories/index.blade.php
@extends('layouts.admin')

@section('content')

    @if(Session::has('deleted_category'))
        <p class="bg-danger">{{session('deleted_category')}}</p>
    @endif

    <h1>Categories</h1>

    <div class="row">
        @include('includes.form_error')
    </div>

    <style>
        
        table {
            font-family: arial, sans-serif;
            border-collapse: collapse;
            width: 100%;
        }

        td, th {
            border: 1px solid #dddddd;
            text-align: left;
            padding: 8px;
        }

        tr:nth-child(even) {
            background-color: #dddddd;
        }

    </style>

    <div class="row">

        <div class="col-sm-6">
            
            {{ Form::open(['method'=>'POST', 'action'=>'AdminCategoriesController@store']) }}
                
                <div class="form-group">
                    {{ Form::label('name', 'Name:') }}
                    {{ Form::text('name', null, ['class'=>'form-control'])}}
            
                </div>
                <div class="form-group">
                    {{ Form::submit('Create Category', ['class'=>'btn btn-primary col-sm-6'])}}
                </div>

            {{ Form::close() }}

        </div>
    
        <div class="col-sm-6">
        
            <table style="width:100%">
                <tr>
                    <th>Id</th>
                    <th>Name</th>
                    <th>Created</th>
                </tr>

                @if($categories)
                    @foreach($categories as $category)
                <tr>
                    <td>{{$category->id}}</td>
                    <td><a href="{{route('categories.edit', $category->id)}}">{{$category->name}}</a></td>
                    <td>{{$category->created_at ? $category->created_at->diffForHumans() : 'No date'}}</td>
                </tr>
                    @endforeach
                @endif
            </table>

        </div>

    </div>



@endsection